# General
site_name: Shippable Docs
repo_url: https://github.com/Shippable/docsv2

# Paths
docs_dir: sources
theme_dir: theme/shippable

#Google Analytics
google_analytics: ['UA-50610279-1', 'auto']

# Pages
pages:
- Overview:
  - What is Shippable?: index.md
  - FAQ: faq.md
- Continuous Integration (CI):
  - Overview: ci/overview.md
  - What is supported?: ci/supported.md
  - Running a build: ci/runFirstBuild.md
  - Build configuration: ci/shippableyml.md
  - Languages:
    - Node.js: ci/languages/node.md
    - Python: ci/languages/python.md
    - Java: ci/languages/java.md
    - Clojure: ci/languages/clojure.md
    - Ruby: ci/languages/ruby.md
    - Go: ci/languages/go.md
    - PHP: ci/languages/php.md
    - Scala: ci/languages/scala.md
    - C: ci/languages/objc.md
    - Custom Images: ci/languages/customImages.md
  - Services:
    - CouchDB: ci/services/couchDB.md
    - Elastic Search: ci/services/elasticSearch.md
    - Kestrel: ci/services/kestrel.md
    - Memcached: ci/services/memcached.md
    - MongoDB: ci/services/mongoDB.md
    - MySQL: ci/services/mySQL.md
    - Neo4j: ci/services/neo4j.md
    - Postgres: ci/services/postgreSQL.md
    - RabbitMQ: ci/services/rabbitMQ.md
    - Redis: ci/services/redis.md
    - RethinkDB: ci/services/rethinkDB.md
    - Riak: ci/services/riak.md
    - Selenium: ci/services/selenium.md
    - SQLite: ci/services/sqlite.md
  - Advanced Options:
    - Environment Variables: ci/advancedOptions/environmentVariables.md
    - Including/Excluding branches: ci/advancedOptions/branches.md
    - Matrix builds: ci/advancedOptions/matrixBuilds.md
    - Caching: ci/advancedOptions/caching.md
    - Using git submodules: ci/advancedOptions/gitSubmodules.md
    - Shippable_retry: ci/advancedOptions/retry.md
    - Running builds on your own machines (BYON): ci/advancedOptions/byon.md
    - Images: ci/advancedOptions/images.md
    - Timeouts: ci/advancedOptions/timeouts.md
    - Node Machine Images: ci/advancedOptions/machineImages.md
  - Integrations:
    - Source Control Systems:
      - Overview: ci/integrations/scm/scmOverview.md
      - GitHub: ci/integrations/scm/github.md
      - GitHub Enterprise: ci/integrations/scm/githubEnterprise.md
      - Bitbucket: ci/integrations/scm/bitbucket.md
      - Bitbucket Server: ci/integrations/scm/bitbucketServer.md
      - GitLab: ci/integrations/scm/gitlab.md
    - Notifications:
      - Slack: ci/integrations/notifications/slack.md
      - Email: ci/integrations/notifications/email.md
      - HipChat: ci/integrations/notifications/hipchat.md
      - IRC: ci/integrations/notifications/irc.md
    - Image Registries:
      - Docker Hub: ci/integrations/imageRegistries/dockerHub.md
      - Docker Trusted Registry: ci/integrations/imageRegistries/dockerTrustedRegistry.md
      - Amazon EC2 Container Registry (ECR): ci/integrations/imageRegistries/ecr.md
      - Google Container Registry (GCR): ci/integrations/imageRegistries/gcr.md
      - Quay.io: ci/integrations/imageRegistries/quay.md
      - Any Private Registry: ci/integrations/imageRegistries/privateRegistry.md
    - Container Services:
      - Amazon EC2 Container Service (ECS): ci/integrations/containerServices/ecs.md
      - Google Container Engine (GKE): ci/integrations/containerServices/gke.md
      - Docker Cloud: ci/integrations/containerServices/dockerCloud.md
      - Docker Datacenter: ci/integrations/containerServices/dockerDatacenter.md
    - Deploy:
      - AWS Elastic Beanstalk: ci/integrations/deploy/eb.md
      - Webhooks: ci/integrations/deploy/webhooks.md
    - Keys:
      - SSH: ci/integrations/keys/ssh.md
      - PEM:  ci/integrations/keys/pem.md
  - Permissions: ci/permissions.md
  - Troubleshooting CI: ci/troubleshoot.md
- Pipelines:
  - Overview: pipelines/overview.md
  - Resources: pipelines/resources.md
  - Jobs: pipelines/jobs.md
  - Triggers: pipelines/triggers.md
  - Sample: tutorials/pipelines/samplePipeline.md
  - FAQ: pipelines/faq.md
  - Troubleshooting: pipelines/troubleshoot.md
- Navigating the UI:
  - Home: navigatingUI/home.md
  - Account:
    - Account: navigatingUI/accountSettings/accounts.md
    - Integrations: navigatingUI/accountSettings/integrations.md
    - Cards: navigatingUI/accountSettings/cards.md
    - Images: navigatingUI/accountSettings/images.md
    - API: navigatingUI/accountSettings/api.md
  - Subscription:
    - CI: navigatingUI/subscriptions/ci.md
    - Pipelines: navigatingUI/subscriptions/pipelines.md
    - Settings: navigatingUI/subscriptions/settings.md
  - Project:
    - Status: navigatingUI/projects/status.md
    - Settings: navigatingUI/projects/settings.md
  - Build:
    - Overview: navigatingUI/builds/overview.md
    - Detail: navigatingUI/builds/detail.md
- API:
  - Overview: api/overview.md
  - Account routes: api/account.md
  - Subscription routes: api/subscription.md
  - Project routes: api/project.md
  - Job routes: api/job.md
  - Run routes: api/run.md
  - Status Code Mapping: api/statusMapping.md
- Tutorials:
  - Continuous Integration (CI) tutorials:
    - Adding Account Integrations: tutorials/ci/integrations/addAccountIntegrations.md
    - Run a sample CI build: tutorials/ci/runSampleCIBuild.md
    - Monitor your Docker Images for updates: tutorials/ci/howToMonitorDockerImages.md
    - Advanced Options Tutorials:
      - Setting up matrix builds: test.md
      - Using matrix to parallelize builds: test.md
      - Using Caching: test.md
      - Setting up git submodules: test.md
      - Using Shippable_retry: test.md
      - Pushing to multiple registries: test.md
      - Pushing multiple tags: test.md
      - Overriding the default build image: test.md
      - Building your CI image: test.md
      - Pulling your CI image from a Docker registry: test.md
      - Running multiple docker push: test.md
    - Integrations Tutorials:
      - Source Control Systems Tutorials:
        - Linking GitHub and Bitbucket accounts on Shippable: tutorials/ci/integrations/scm/linkGitHubAndBitbucket.md
        - GitHub: tutorials/ci/integrations/scm/usingGitHub.md
        - GitHub Entrprise: tutorials/ci/integrations/scm/usingGitHubEnterprise.md
        - Bitbucket: tutorials/ci/integrations/scm/usingBitbucket.md
        - Bitbucket Server: tutorials/ci/integrations/scm/usingBitbucketServer.md
        - GitLab: tutorials/ci/integrations/scm/usingGitLab.md
      - Notifications Tutorials: test.md
      - Image Registries Tutorials: test.md
      - Container Services Tutorials:
        - Docker Datacenter: tutorials/ci/integrations/containerServices/usingDockerDatacenter.md
      - Deploy Tutorials:
        - Heroku: tutorials/ci/integrations/deploy/usingHeroku.md
        - OpsWorks: tutorials/ci/integrations/deploy/usingOpsWorks.md
        - Code Deploy: tutorials/ci/integrations/deploy/usingCodeDeploy.md
        - Digital Ocean: tutorials/ci/integrations/deploy/usingDigitalOcean.md
      - Keys Tutorials: test.md
  - Pipelines Tutorials:
    - How to add resources: tutorials/pipelines/howToAddSyncRepos.md
    - Deploying a sample appliation: tutorials/pipelines/samplePipeline.md
