# General
site_name: Shippable Documentation
repo_url: https://github.com/Shippable

# Paths
docs_dir: sources
theme_dir: theme/shippable

#Google Analytics
google_analytics: ['UA-50610279-1', 'auto']

# Pages
pages:
- Overview:
  - What is Shippable?: index.md
  - FAQ: faq.md
- Continuous Integration (CI):
  - Overview: ci_overview.md
  - Subscriptions: ci_subscriptions.md
  - Projects: ci_projects.md
  - Builds: ci_builds.md
  - Configuring your build: ci_configure.md
  - Language help: ci_languages.md
  - Docker support: ci_docker.md
  - Monitor your Docker images: lighthouse.md
  - Running builds on your machines: ci_byoh.md
  - Running a sample build: gs_ci_sample.md
  # - CI FAQ: ci_faq.md
  - CI Troubleshooting: ci_troubleshoot.md
- Pipelines:
  - Overview: pipelines/overview.md
  - Pipeline Status: pipelines_subscriptions.md
  - Configuring and managing pipelines: pipelines_configure.md
  - Deploy a sample app: gs_deploy_sample.md
  - Pipelines FAQ: pipelines_faq.md
- Integrations:
  - Overview: int_overview.md
  - Source control providers: int_scm.md
  - Docker registries: int_docker_registries.md
  - Container services: int_container_services.md
  - PaaS/IaaS providers: int_paas_iaas_providers.md
  - Notification providers: int_notifications.md
  - Keys: int_keys.md
- API: api.md
- Tutorials:
  - Running a sample CI build: gs_ci_sample.md
  - Deploying a sample appliation: test.md
  - Source Control System:
    - Using GitHub: test.md
    - Using GitHub Enterprise: test.md
    - Using Bitbucket: test.md
    - Using Bitbucket Server: ht_using_bitbucket_server.md
    - Using GitLab: ht_using_gitlab.md
    - Linking GitHub and Bitbucket accounts: ht_link_gh_and_bb.md
  - Amazon:
    - Deploy to AWS CodeDeploy: ht_codedeploy.md
    - Deploy to Amazon Opsworks: ht_opsworks.md
    - Deploy to Amazon EC2 Container Registry (ECR): test.md
    - Deploy to AWS Elastic Beanstalk: test.md
    - Deploy to Amazon EC2 Container Service (ECS): test.md
  - Google:
    - Deploy to Google Container Registry (GCR): test.md
    - Deploy to Google Container Engine (GKE): test.md
  - Docker:
    - Deploy to Docker Hub: test.md
    - Deploy to Docker Trusted Registry: test.md
    - Deploy to Docker Datacenter: ht_docker_datacenter.md
    - Deploy to Docker Cloud: test.md
  - Microsoft:
    - Deploy to DC/OS on Azure: test.md
    - Deploy to Docker Swarm on Azure: test.md
    - Deploy to Azure Container Service (ACS): test.md
  - Deploy to Quay.io: test.md
  - Deploy to any private registry: test.md
  - Languages Based:
    - test: test.md
  - Pushing to multiple registries: test.md
  - Pushing multiple tags: test.md
  - Overriding the default build image: test.md
  - Building your CI image: test.md
  - Pulling your CI image from a Docker registry: test.md
  - Setting up matrix builds: test.md
  - Setting up git submodules: test.md
  - Using Shippable_retry: test.md
  - Using Caching: test.md
  - Using matrix to parallelize builds: test.md
  - Running multiple docker push: test.md
  - Deploy to Heroku: ht_heroku.md
  - Deploy to Digital Ocean: ht_digitalocean.md
