# General
site_name: Shippable Docs
repo_url: https://github.com/Shippable/docsv2

# Paths
docs_dir: sources
theme_dir: theme/shippable

#Google Analytics
google_analytics: ['UA-50610279-1', 'auto']

# Pages
pages:
- Overview:
  - What is Shippable?: index.md
  - FAQ: faq.md
- Continuous Integration (CI):
  - Overview: ci/overview.md
  - What is supported?: ci/supported.md
  - Running a build: ci/runFirstBuild.md
  - Build configuration: ci/shippableyml.md
  - Languages:
    - Node.js: ci/languages/node.md
    - Python: ci/languages/python.md
    - Java: ci/languages/java.md
    - Clojure: ci/languages/clojure.md
    - Ruby: ci/languages/ruby.md
    - Go: ci/languages/go.md
    - PHP: ci/languages/php.md
    - Scala: ci/languages/scala.md
    - C: ci/languages/objc.md
    - Custom Images: ci/languages/customImages.md
  - Services:
    - CouchDB: ci/services/couchDB.md
    - Elastic Search: ci/services/elasticSearch.md
    - Memcached: ci/services/memcached.md
    - MongoDB: ci/services/mongoDB.md
    - MySQL: ci/services/mySQL.md
    - Neo4j: ci/services/neo4j.md
    - Postgres: ci/services/postgreSQL.md
    - RabbitMQ: ci/services/rabbitMQ.md
    - Redis: ci/services/redis.md
    - RethinkDB: ci/services/rethinkDB.md
    - Riak: ci/services/riak.md
    - Selenium: ci/services/selenium.md
    - SQLite: ci/services/sqlite.md
  - Advanced Options:
    - Environment Variables: ci/advancedOptions/environmentVariables.md
    - Including/Excluding branches: ci/advancedOptions/branches.md
    - Matrix builds: ci/advancedOptions/matrixBuilds.md
    - Caching: ci/advancedOptions/caching.md
    - Using git submodules: ci/advancedOptions/gitSubmodules.md
    - Shippable_retry: ci/advancedOptions/retry.md
    - Running builds on your own machines (BYON): ci/advancedOptions/byon.md
    - Images: ci/advancedOptions/images.md
    - Timeouts: ci/advancedOptions/timeouts.md
    - Node Machine Images: ci/advancedOptions/machineImages.md  
  - Permissions: ci/permissions.md
  - Troubleshooting CI: ci/troubleshoot.md
- Continuous Deployment Pipelines:
  - Overview: pipelines/overview.md
  - Resources: pipelines/resources.md
  - Jobs: pipelines/jobs.md
  - Triggers: pipelines/triggers.md
  - Sample: pipelines/samplePipeline.md
  - FAQ: pipelines/faq.md
  - Troubleshooting: pipelines/troubleshoot.md
- Integrations: 
  - Source Control Systems: 
    - Overview: integrations/scm/scmOverview.md
    - GitHub: integrations/scm/github.md
    - GitHub Enterprise: integrations/scm/githubEnterprise.md
    - Bitbucket: integrations/scm/bitbucket.md
    - Bitbucket Server: integrations/scm/bitbucketServer.md
    - GitLab: integrations/scm/gitlab.md
  - Notifications: 
    - Slack: integrations/notifications/slack.md
    - Email: integrations/notifications/email.md
    - HipChat: integrations/notifications/hipchat.md
    - IRC: integrations/notifications/irc.md
  - Image Registries: 
    - Docker Hub: integrations/imageRegistries/dockerHub.md
    - Docker Trusted Registry: integrations/imageRegistries/dockerTrustedRegistry.md
    - Amazon EC2 Container Registry (ECR): integrations/imageRegistries/ecr.md
    - Google Container Registry (GCR): integrations/imageRegistries/gcr.md
    - Quay.io: integrations/imageRegistries/quay.md
    - Any Private Registry: integrations/imageRegistries/privateRegistry.md
  - Container Services: 
    - Amazon EC2 Container Service (ECS): integrations/containerServices/ecs.md
    - Google Container Engine (GKE): integrations/containerServices/gke.md
    - Docker Cloud: integrations/containerServices/dockerCloud.md
    - Docker Datacenter: integrations/containerServices/dockerDatacenter.md
  - Deploy: 
    - AWS Elastic Beanstalk: integrations/deploy/eb.md
    - Webhooks: integrations/deploy/webhooks.md
  - Keys:
    - SSH: integrations/keys/ssh.md
    - PEM:  integrations/keys/pem.md  
- Navigating the UI:
  - Home: navigatingUI/home.md
  - Account:
    - Account: navigatingUI/accountSettings/accounts.md
    - Integrations: navigatingUI/accountSettings/integrations.md
    - Cards: navigatingUI/accountSettings/cards.md
    - Images: navigatingUI/accountSettings/images.md
    - API: navigatingUI/accountSettings/api.md
  - Subscription:
    - CI: navigatingUI/subscriptions/ci.md
    - Pipelines: navigatingUI/subscriptions/pipelines.md
    - Settings: navigatingUI/subscriptions/settings.md
  - Project:
    - Status: navigatingUI/projects/status.md
    - Settings: navigatingUI/projects/settings.md
  - Build:
    - Overview: navigatingUI/builds/overview.md
    - Detail: navigatingUI/builds/detail.md
- API:
  - Overview: api/overview.md
  - Account routes: api/account.md
  - Subscription routes: api/subscription.md
  - Project routes: api/project.md
  - Job routes: api/job.md
  - Run routes: api/run.md
  - Status Code Mapping: api/statusMapping.md
- Tutorials: 
  - CI Tutorials: 
    - Adding Account Integrations: tutorials/ci/integrations/addAccountIntegrations.md
    - Run a sample CI build: tutorials/ci/runSampleCIBuild.md
    - Monitor your Docker Images for updates: tutorials/ci/howToMonitorDockerImages.md
    - Integrations tutorials: 
      - Source Control Systems Tutorials: 
        - Linking GitHub and Bitbucket accounts on Shippable: tutorials/ci/integrations/scm/linkGitHubAndBitbucket.md
        - Building GitHub Enterprise repos: tutorials/ci/integrations/scm/usingGitHubEnterprise.md
        - Building Bitbucket Server repos: tutorials/ci/integrations/scm/usingBitbucketServer.md
        - Building GitLab repos: tutorials/ci/integrations/scm/usingGitLab.md
      - Container Services Tutorials: 
        - Using Docker Datacenter: tutorials/ci/integrations/containerServices/usingDockerDatacenter.md
      - Deploy Tutorials: 
        - Using Heroku: tutorials/ci/integrations/deploy/usingHeroku.md
        - Using OpsWorks: tutorials/ci/integrations/deploy/usingOpsWorks.md
        - Using Code Deploy: tutorials/ci/integrations/deploy/usingCodeDeploy.md
        - Using Digital Ocean: tutorials/ci/integrations/deploy/usingDigitalOcean.md
  - Pipelines Tutorials:  
    - Using integrations with a runSh job: tutorials/pipelines/runShUseIntegrations.md
    - Deploying a sample application: tutorials/pipelines/samplePipeline.md
